export default {
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "18c41134": [() => import(/* webpackChunkName: "18c41134" */ "@site/docs/tutorial-basics/markdown-features.mdx"), "@site/docs/tutorial-basics/markdown-features.mdx", require.resolveWeak("@site/docs/tutorial-basics/markdown-features.mdx")],
  "47418893": [() => import(/* webpackChunkName: "47418893" */ "/Users/nikitabatryncha/Desktop/mf/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json"), "/Users/nikitabatryncha/Desktop/mf/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/nikitabatryncha/Desktop/mf/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "935f2afb": [() => import(/* webpackChunkName: "935f2afb" */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "d538132a": [() => import(/* webpackChunkName: "d538132a" */ "@site/docs/tempo/md-install.md"), "@site/docs/tempo/md-install.md", require.resolveWeak("@site/docs/tempo/md-install.md")],
  "e5888d0c": [() => import(/* webpackChunkName: "e5888d0c" */ "/Users/nikitabatryncha/Desktop/mf/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json"), "/Users/nikitabatryncha/Desktop/mf/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json", require.resolveWeak("/Users/nikitabatryncha/Desktop/mf/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json")],};
